name: DoNotDoThis
version: '${project.version}'
description: 'A game plugin.'
main: me.serliunx.DoNotDoThis.Main
api-version: 1.17
authors: [ SerLiunx ]
softdepend: [PlaceholderAPI]
commands:
  donotdothis:
    aliases: [dnd, dndt]
    description: main command for DoNotDoThis.